{
  "openapi": "3.0.2",
  "info": {
    "title": "Pixelarium",
    "version": "1.0.0",
    "contact": {
      "name": "Kadek Nova Cahaya Putra",
      "email": "Kadeknovacahayaputra@gmail.com"
    },
    "license": {
      "name": "MIT license",
      "url": "https://github.com/ItsNvaa/Pixelarium/blob/main/LICENSE"
    },
    "description": "The Infinite Pixels Experience."
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Development Environment"
    },
    { "url": "http://localhost:8000", "description": "Staging Environment" },
    { "url": "api.pixelarium.my.id", "description": "Production Environment" }
  ],
  "paths": {
    "/auth/v1/google": {
      "summary": "Google Authentication",
      "get": {
        "deprecated": false,
        "summary": "Google Authentication",
        "operationId": "loginWithGoolge",
        "tags": ["Authentication"],
        "description": "Sign in with Google Provider",
        "responses": {
          "302": {
            "description": "Redirected to pixelarium dashboard"
          },
          "301": {
            "description": "Redirected to pixelarium login page while the authentication process is failed"
          },
          "400": {
            "description": "The Login Session Was Failed."
          }
        }
      }
    },
    "/v1/auth/github": {
      "summary": "Github Authentication",
      "get": {
        "summary": "Github Authentication",
        "description": "Sign in with Github Provider",
        "tags": ["Authentication"],
        "deprecated": false,
        "operationId": "loginWithGithub",
        "responses": {
          "400": {
            "description": "The Login Session Was Failed."
          },
          "302": {
            "description": "Redirected to pixelarium dashboard"
          }
        }
      }
    },
    "/v1/auth/token": {
      "summary": "Refresh Session Token Rotation",
      "get": {
        "description": "Get new access token by using refresh token.",
        "summary": "Refresh Session Token Rotation",
        "tags": ["Authentication"],
        "deprecated": false,
        "operationId": "token",
        "parameters": [
          {
            "$ref": "#/components/parameters/sessionTokenCookiesParams"
          }
        ],
        "responses": {
          "401": {
            "$ref": "#/components/responses/unauthorizedUser"
          },
          "422": {
            "description": "The session token is invalid"
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "200": {
            "description": "Newly generated JWT token and a cookie for tracking user sessions.",
            "content": {
              "application/json": {
                "example": {
                  "token": {
                    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ....",
                    "expiresInSecond": 1800,
                    "expiresDate": 1703852872386
                  },
                  "generated": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/auth/logout": {
      "summary": "Logout User API Endpoint",
      "post": {
        "deprecated": false,
        "summary": "Logout User API Endpoint",
        "description": "Logout User",
        "operationId": "logoutUser",
        "tags": ["Authentication"],
        "parameters": [
          {
            "$ref": "#/components/parameters/sessionTokenCookiesParams"
          }
        ],
        "responses": {
          "401": {
            "$ref": "#/components/responses/unauthorized"
          },
          "400": {
            "description": "Cannot find user request!"
          },
          "200": {
            "description": "Success Logouted User",
            "content": {
              "application/json": {
                "example": {
                  "logutedUser": {
                    "id": 1,
                    "provider_id": 623977,
                    "name": "ItsNvaa",
                    "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                    "type": "User",
                    "bio": "The real loser is somebody that so afraid of not wining, they don't even try.",
                    "site_admin": false,
                    "createdAt": "2023-12-29T02:04:38.726Z",
                    "updatedAt": "2023-12-29T02:04:38.726Z"
                  },
                  "logouted": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/users/{name}": {
      "summary": "Get Single User Data",
      "patch": {
        "tags": ["Users"],
        "operationId": "updateUser",
        "deprecated": false,
        "summary": "Update Existing User",
        "description": "Update Existing User By Id",
        "parameters": [
          {
            "$ref": "#/components/parameters/usernameParams"
          }
        ],
        "requestBody": {
          "required": true,
          "description": "User Data",
          "content": {
            "application/json": {
              "example": {
                "name": "John Doe",
                "bio": "My name is John Doe"
              }
            }
          }
        },
        "responses": {
          "400": {
            "$ref": "#/components/responses/userIdValidation"
          },
          "404": {
            "$ref": "#/components/responses/notFound"
          },
          "422": {
            "description": "The image file extension was not supported."
          },
          "200": {
            "description": "Success Updated User Data",
            "content": {
              "application/json": {
                "example": {
                  "updatedUser": {
                    "id": 1,
                    "provider_id": 130564362,
                    "name": "ItsNvaa",
                    "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                    "type": "User",
                    "bio": "The real loser is somebody that so afraid of not wining, they don't even try.",
                    "site_admin": false,
                    "createdAt": "2023-12-29T05:07:55.886Z",
                    "updatedAt": "2023-12-29T05:07:55.886Z"
                  },
                  "updated": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      },
      "get": {
        "deprecated": false,
        "tags": ["Users"],
        "operationId": "singleUser",
        "description": "Get Single User Data From User Name",
        "summary": "Get Single User Data",
        "parameters": [
          {
            "$ref": "#/components/parameters/usernameParams"
          }
        ],
        "responses": {
          "404": {
            "$ref": "#/components/responses/notFound"
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "200": {
            "description": "Returns a single user data by username.",
            "content": {
              "application/json": {
                "example": {
                  "user": {
                    "id": 1,
                    "provider_id": 130564362,
                    "name": "ItsNvaa",
                    "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                    "type": "User",
                    "bio": "The real loser is somebody that so afraid of not wining, they don't even try.",
                    "site_admin": false,
                    "createdAt": "2023-12-29T02:04:38.726Z",
                    "updatedAt": "2023-12-29T02:04:38.726Z"
                  },
                  "isSuccess": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Users"],
        "deprecated": false,
        "operationId": "deleteUser",
        "summary": "Delete Existing User",
        "description": "Delete Existing User By Id",
        "security": [
          {
            "JsonWebTokenAuthorization": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/usernameParams"
          }
        ],
        "responses": {
          "404": {
            "$ref": "#/components/responses/notFound"
          },
          "400": {
            "description": "The ID was not valid."
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "deletedUser": {
                    "id": 1,
                    "provider_id": 130564362,
                    "name": "ItsNvaa",
                    "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                    "type": "User",
                    "bio": "The real loser is somebody that so afraid of not wining, they don't even try.",
                    "site_admin": false,
                    "createdAt": "2023-12-29T02:04:38.726Z",
                    "updatedAt": "2023-12-29T02:04:38.726Z"
                  },
                  "deleted": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/client-keys/generate": {
      "post": {
        "tags": ["Client Keys"],
        "summary": "Generate User Client Keys",
        "deprecated": false,
        "operationId": "generateClientKeys",
        "security": [{ "JsonWebTokenAuthorization": [] }],
        "description": "Generate User Client Keys Credentials",
        "parameters": [
          {
            "$ref": "#/components/parameters/sessionTokenCookiesParams"
          }
        ],
        "responses": {
          "422": {
            "$ref": "#/components/responses/unauthorized"
          },
          "400": {
            "description": "The request cannot be found"
          },
          "201": {
            "description": "Created a new user client keys credentials",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "from": {
                      "id": 1,
                      "provider_id": 130564362,
                      "name": "ItsNvaa",
                      "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                      "type": "User",
                      "bio": "This is my bioooo",
                      "site_admin": false,
                      "createdAt": "2023-12-29T05:07:55.886Z",
                      "updatedAt": "2023-12-29T05:08:57.153Z"
                    }
                  },
                  "created": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/client-keys/{name}": {
      "get": {
        "tags": ["Client Keys"],
        "deprecated": false,
        "security": [{ "JsonWebTokenAuthorization": [] }],
        "operationId": "userClientKeys",
        "summary": "Get User Client Keys",
        "description": "Get User Client Keys From Username",
        "parameters": [
          {
            "$ref": "#/components/parameters/sessionTokenCookiesParams"
          },
          {
            "$ref": "#/components/parameters/usernameParams"
          }
        ],
        "responses": {
          "404": {
            "$ref": "#/components/responses/notFound"
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "from": {
                      "id": 1,
                      "provider_id": 130564362,
                      "name": "ItsNvaa",
                      "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                      "type": "User",
                      "bio": "This is my bioooo",
                      "site_admin": false,
                      "createdAt": "2023-12-29T05:07:55.886Z",
                      "updatedAt": "2023-12-29T05:08:57.153Z"
                    },
                    "client_keys": {
                      "user_client_id": "pxlmid-03924b8ee55911aa...",
                      "user_client_secret": "84f7149615a608302bdcb05076eccd7...."
                    }
                  },
                  "isSuccess": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/client-keys": {
      "delete": {
        "tags": ["Client Keys"],
        "summary": "Delete Existing User Client Keys",
        "deprecated": false,
        "security": [{ "JsonWebTokenAuthorization": [] }],
        "parameters": [
          {
            "$ref": "#/components/parameters/sessionTokenCookiesParams"
          }
        ],
        "operationId": "deleteUSerClientKeys",
        "responses": {
          "401": {
            "$ref": "#/components/responses/unauthorizedUser"
          },
          "404": {
            "description": "Your request doesn't be found"
          },
          "422": {
            "description": "The User Client Secret Ins't Exist."
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "from": {
                      "id": 1,
                      "provider_id": 130564362,
                      "name": "ItsNvaa",
                      "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                      "type": "User",
                      "bio": "This is my bioooo",
                      "site_admin": false,
                      "createdAt": "2023-12-29T05:07:55.886Z",
                      "updatedAt": "2023-12-29T05:08:57.153Z"
                    },
                    "deletedClientKeys": {
                      "user_client_id": "pxlmid-03924b8ee....",
                      "user_client_secret": "84f7149615a608302bdcb05076eccd..."
                    }
                  },
                  "deleted": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/galleries/{name}": {
      "get": {
        "tags": ["Galleries"],
        "summary": "Get User Galleries",
        "deprecated": false,
        "operationId": "gallery",
        "parameters": [
          {
            "$ref": "#/components/parameters/usernameParams"
          }
        ],
        "responses": {
          "404": {
            "$ref": "#/components/responses/notFound"
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "owner": {
                      "id": 1,
                      "provider_id": 130564362,
                      "name": "ItsNvaa",
                      "picture": "https://avatars.githubusercontent.com/u/130564362?v=4",
                      "type": "User",
                      "bio": "The real loser is somebody that so afraid of not wining, they don't even try.",
                      "site_admin": false,
                      "createdAt": "2023-12-29T02:04:38.726Z",
                      "updatedAt": "2023-12-29T02:04:38.726Z"
                    },
                    "gallery": {
                      "id": 5,
                      "user_id": 1,
                      "pictures": [
                        {
                          "id": 3,
                          "title": "example picture",
                          "description": "this is a description",
                          "url": "https://example.com/img/galleries/pictures/image.png",
                          "is_favorited": false,
                          "filename": "image.png",
                          "extension": ".png",
                          "is_private": false,
                          "gallery_id": 5,
                          "album_picture_id": null,
                          "favorite_id": null,
                          "createdAt": "2023-12-29T06:33:47.737Z",
                          "updatedAt": "2023-12-29T06:34:51.923Z"
                        }
                      ],
                      "createdAt": "2023-12-24T02:17:41.549Z",
                      "updatedAt": "2023-12-24T02:17:41.549Z"
                    },
                    "total_gallery_pictures": 2
                  },
                  "isSuccess": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    },
    "/v1/galleries/search": {
      "get": {
        "tags": ["Galleries"],
        "summary": "Search for galleries pictures by picture title ",
        "deprecated": false,
        "operationId": "searchPicturesGalery",
        "parameters": [
          {
            "$ref": "#/components/parameters/searchParams"
          }
        ],
        "responses": {
          "404": {
            "$ref": "#/components/responses/emptyRequestBodyValidationError"
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "200": {
            "description": "A list of found gallery's pictures.",
            "content": {
              "application/json": {
                "example": {
                  "data": {
                    "pictures": [
                      {
                        "id": 3,
                        "title": "example picture",
                        "description": "this is a description",
                        "url": "https://example.com/img/galleries/pictures/image.png",
                        "is_favorited": false,
                        "filename": "image.png",
                        "extension": ".png",
                        "is_private": false,
                        "gallery_id": 5,
                        "album_picture_id": null,
                        "favorite_id": null,
                        "createdAt": "2023-12-29T06:33:47.737Z",
                        "updatedAt": "2023-12-29T06:34:51.923Z"
                      }
                    ],
                    "total_found": 1
                  },
                  "isSuccess": true,
                  "status": "OK"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "JsonWebTokenAuthorization": {
        "scheme": "bearer",
        "bearerFormat": "Bearer",
        "description": "Authentication for User",
        "type": "http"
      }
    },
    "parameters": {
      "sessionTokenCookiesParams": {
        "name": "session",
        "allowEmptyValue": false,
        "deprecated": false,
        "description": "Refresh Session Token",
        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ....",
        "in": "cookie",
        "required": true,
        "schema": {
          "deprecated": false,
          "type": "string"
        }
      },
      "usernameParams": {
        "name": "name",
        "allowEmptyValue": false,
        "deprecated": false,
        "description": "User Name Data",
        "in": "path",
        "required": true,
        "example": "ItsNvaa",
        "schema": {
          "deprecated": false,
          "type": "string"
        }
      },
      "userIdParams": {
        "name": "id",
        "allowEmptyValue": false,
        "deprecated": false,
        "description": "User Id Data",
        "in": "path",
        "required": true,
        "example": 1,
        "schema": {
          "deprecated": false,
          "type": "number"
        }
      },
      "searchParams": {
        "name": "q",
        "allowEmptyValue": false,
        "deprecated": false,
        "description": "Search Query",
        "in": "query",
        "required": true,
        "example": "Pictures title",
        "schema": {
          "deprecated": false,
          "type": "string"
        }
      }
    },
    "responses": {
      "notFound": {
        "description": "Oops! The data you are looking for could not be found."
      },
      "badRequest": {
        "description": "Oops! Your request cannot be processed due to a bad request. Please check your input and try again."
      },
      "unauthorizedUser": {
        "description": "The user must be login first!"
      },
      "unauthorized": {
        "description": "You are not authorized to access this resource. Please provide valid credentials or authentication."
      },
      "userIdValidation": {
        "description": "The ID was not valid."
      },
      "emptyRequestBodyValidationError": {
        "description": "The input fields must be filled."
      },
      "validateInvalidRequestBodyObject": {
        "description": "Validate if the request body object is contains invalid request body field"
      }
    }
  }
}
